### ISSUE TITLE
First attempt at CHAR18, Sort code "Common"

### ISSUE THREAD

**Issue by theypsilon** [ThreepwoodLeBrush/Names_MiSTer#1]
I tried to convert CHAR28_Manufacturer_US to CHAR18.

This is what I got: https://github.com/ThreepwoodLeBrush/Names_MiSTer/blob/master/names_CHAR18_System_US.txt

As you see, I put "System" as Sort code (that name should be discussed here btw, maybe some other name is more appropriate).

I'll tell you what I did to set the names for "System" and CHAR18: 
1. I included some Manufacturers when they seemed to belong to the system name. For example Atari 2600 or Commodore 64. To double check that, I was looking for the name in Wikipedia, english version. 99% of the times the name I got there is 18CHAR compatible, so it was fantastic.
2. When a core had additional computers implemented in it, but those didn't fit in the name, I removed those additional ones, or at least some of them.
3. When the system name didn't fit the CHAR18, I abbreviate following the Core name. This was only the case of TI-99/4A.

I think this criteria could be improved. Hopefully we can find a more robust set of rules to determine the name of this Sort code. Wikipedia for example, worked for me this time, but I don't think is a good idea.

For me CHAR18 is important, as I think is a sane default for the tool I'm working on.

**Comment by ThreepwoodLeBrush** [comment]
Your CHAR18 file looks great!

"System" does indeed not cover it, but maybe "common" name? Many of these systems were refered to by shorter handles, sometimes with, sometimes without a company name, like the example of "Atari 2600" and "Game Gear"?

The rules you applied are quite good already and match what I would do. I would suggest to make a rules.txt that contains the shortening rules that we can build by giving it some though and over time adapt them by experience.

If the company that built a system still exists there is a good chance that they have some company history or pages about their systems. That won't be possible for all, but when available should take precedence over Wikipedia. I need to double check names again doing this, but for now we have a set of files that work as a test.

I will add the character count markers to the other files, they are really handy to have.

**Comment by theypsilon** [comment]
Renamed to Common: https://github.com/ThreepwoodLeBrush/Names_MiSTer/blob/master/names_CHAR18_Common_US.txt
Added rules.txt: https://github.com/ThreepwoodLeBrush/Names_MiSTer/blob/master/rules_CHAR18_Common.txt
