### ISSUE TITLE
Support for SGB

### ISSUE THREAD

**Issue by MorkMikael** [ThreepwoodLeBrush/Names_MiSTer#10]
hi can you add support for SGB core and Gamate
SGB: Nint. SGB
Gamate: Bit Corp. Gamate
Gamate: UMC. Gamate

best regards
Mork

**Comment by ThreepwoodLeBrush** [comment]
Done and credited to you. Sorry it took a while :)

**Comment by MorkMikael** [comment]
bug SGB needs to be in capital letters or it wont work
SGB:  Nint. Super GB

best regaards
Mork

**Comment by MorkMikael** [comment]
il only comment on cores that is downloaded for mister update all or download 1.5

**Comment by ThreepwoodLeBrush** [comment]
Sure thing and thank you very much for contributing! :)
