### ISSUE TITLE
Zaxxon appears as “18 common” on MiSTer menu

### ISSUE THREAD

**Issue by thiagoauler** [ThreepwoodLeBrush/Names_MiSTer#11]
Just found a little bug, in names.txt, Zaxxon is created with wrong name.
Having a good look in names.cvs I believe the reason is pretty simple:

Zaxxon                        ;SEGA - Zaxxon                       ;zaxxon:18_Common_EU

Note the “zaxxon” is lowercase!
It should be Zaxxon:18_Common_EU, so when processing the cvs file, names.txt will get correctly the indexed “SEGA - Zaxxon” from EU.

**Comment by ThreepwoodLeBrush** [comment]
Thanks a lot for not only reporting the issue, but finding the cause as well! Zaxxon appears correct now in all names.txt-variants.
