### ISSUE TITLE
Missing Benesse Pocket Challenge V2

### ISSUE THREAD

**Issue by w00tazn** [ThreepwoodLeBrush/Names_MiSTer#14]
Now that MiSTer-devel / Distribution_MiSTer includes a .mgl file for Pocket Challenge V2. It would be nice if the names scripts would be updated to include updated names for this aliased core since Downloader will be pulling this down by default and the name will show up in Menu without an updated name to match the downloader config.

https://github.com/MiSTer-devel/Distribution_MiSTer/tree/main/_Console

**Comment by ThreepwoodLeBrush** [comment]
Hello w00tazn,

Thank you for pointing the missing core out. I just added it to names.txt. With the 18-character variants of names-files it is not very pretty, but all I can do sadly. 28 character files look fine.

Regards
Threepwood
