### ISSUE TITLE
Let's see what can we do with the Arcade names

### ISSUE THREAD

**Issue by theypsilon** [ThreepwoodLeBrush/Names_MiSTer#15]
There has been an issue with the arcade names since a change was introduced in the MiSTer firmware some months ago. 

The change allows names.txt to work with MRA and MGL files, and this had unintended consequences for the names.txt files that we generated because simple MRA names, such as Arkanoid.mra that had a matching names.txt entry for the arcade core, would be renamed as if it was a core, and this is unintended, and not what users expect since the names.txt Arkanoid name entry provided by @PigSaint is meant to name the core itself and not the game.

The fix is simple, removing all the arcade names from the names.csv file. But since I'm using these to provide better names in the Arcade Organizer, and @PigSaint did a lot of work on maintaining them, I'd like to move them to another place, not just remove them.

My proposal for a comprehensive solution is moving the arcade names out from this repository to somewhere else, probably a repository from @PigSaint or the repository of the Arcade Organizer itself. That way, you can focus on the non-arcade names.txt as usual, without any disturbance, and users won't experience this problem anymore. Alternatively, we could think of a way to maintain the arcade names here in this repository but in another file named "arcade_names.csv" that would generate a bunch of arcade_names_*.txt files. This is a less clean solution, so I favor the former one.

I would like to hear what you think about this @ThreepwoodLeBrush , since you are the maintainer of this repository. After we decide, I'll take care of the scripts as usual.

**Comment by ThreepwoodLeBrush** [comment]
Hi theypsilon, sorry for the wait, it was a busy week.

Thanks for explaining, I see the problem. If the best solution is to move the arcade names to another repository, then please go ahead.

**Comment by theypsilon** [comment]
Done.

The arcade names have been removed from here: [#75a0dbef34f9c8f3dfd5d1815049678ac6e1a722](https://github.com/ThreepwoodLeBrush/Names_MiSTer/commit/75a0dbef34f9c8f3dfd5d1815049678ac6e1a722)

And now they are in this repository: https://github.com/PigSaint/ArcadeNames_MiSTer

Thanks for your input!
