### ISSUE TITLE
Game and Watch, and MegaDrive core naming

### ISSUE THREAD

**Issue by theypsilon** [ThreepwoodLeBrush/Names_MiSTer#16]
Lately, we have been getting different cores for the same systems.

- Game and Watch: Developer agg23 created this new core (not on MiSTer-devel). It uses the same names.txt as the official one, so people have been a bit confused: 
<img width="647" alt="image" src="https://github.com/ThreepwoodLeBrush/Names_MiSTer/assets/852246/c3233f10-2e86-4a5f-bc14-e9399ec84060">

I suggest to name the one from agg23 as "Game and Watch agg23" or something similar to make it less ambiguous.

- MegaDrive: Sorgelig just published the new core MegaDrive in MiSTer-devel, a port from Nuked-MD. I'm unsure how to name this one differently from the Genesis core. But maybe we could also point out the author's name (Nuked-MD), or we could point out that it's a v2, or a new (better) version of the system.

Not very easy to decide on this, especially for the MegaDrive core. But I trust you'll make a good decision as usual! Let me know if you need any help

**Comment by ThreepwoodLeBrush** [comment]
@wizzomafizzo The names files are not purely static, there can always be some improvements, especially in the common name variants.

@theypsilon Thanks for the headsup, the limitiations of the MiSTer UI make it more difficult to keep this consistent and pretty, but I feel I got it as good as it gets. At least now the cores are easy to distinguish.

Please close the issues, unless you have suggestions on how to improve some names further or want to comment more.

**Comment by wizzomafizzo** [comment]
@ThreepwoodLeBrush Sorry, I meant static as in their interaction with main (unless I misunderstand that too). I didn't mean to imply anything at all about the project! I think it's great

**Comment by theypsilon** [comment]
Love the changes, thanks for everything!
