### ISSUE TITLE
Mega Drive core naming 

### ISSUE THREAD

**Issue by Yamato-san** [ThreepwoodLeBrush/Names_MiSTer#23]
Hello!
theypsilon recently provided a new download filter to remove the old Genesis core. As many MiSTer users are likely to exclude the old core and just keep the new „nuked“ core, I suggest to name the cores as follows:

New core simply „Mega Drive“

Old core „Genesis (old)“ 

Sorgelig already closed the GitHub repository of the old core as archived and read-only, see here: https://github.com/MiSTer-devel/Genesis_MiSTer

Best regards
Yamato

**Comment by ThreepwoodLeBrush** [comment]
Hi Yamato,

thank you very much for pointing the change out! I updated the names.txt-files as per your suggestion and credited you in the commit comment.

Kind Regards
ThreepwoodLeBrush
