### ISSUE TITLE
Sinden cores?

### ISSUE THREAD

**Issue by IdiotBlueMage** [ThreepwoodLeBrush/Names_MiSTer#26]
Mrlightgun's cores for the Sinden lightgun are pretty self explanatory.  Something like this I think?

Atari7800_Sinden: Atari 7800 Sinden
NES_Sinden: Nintendo NES Sinden
SNES_Sinden: Nintendo Super NES Sinden
SMS_Sinden: SEGA Master System Sinden
Genesis_Sinden: SEGA Genesis Sinden (old)
MegaDrive_Sinden: SEGA Genesis Sinden
MegaCD_Sinden: SEGA CD Sinden
PSX_Sinden: Sony PlayStation Sinden

(Probably in the future) Saturn_Sinden: SEGA Saturn Sinden

I'm using Manufacturer US as a base, so these might be too long.

**Comment by ThreepwoodLeBrush** [comment]
They are added now. I would have loved to add "Sinden" to them, but the MiSTer-UI does not offer enough space for this in most cases. For consistency the cores are marked with "(S)" where possible and otherwise with "S". The Char 54 variant contains a proper second line of "Sinden Lightgun".
