### ISSUE TITLE
Arcade cores can be renamed too thanks to the Arcade Organizer

### ISSUE THREAD

**Issue by theypsilon** [ThreepwoodLeBrush/Names_MiSTer#3]
So, in case you don't know about the Arcade Organizer. It is a tool that creates a folder at _Arcade/_Organized containing links to your installed arcades. The links are organized in a way that looks like a SmokeMonster pack, so it's quite handy to use. That tool lives here: https://github.com/MAME-GETTER/_arcade-organizer

There is a 'Cores' folder in the folder structure created by the organizer. There, as the name says, arcades are grouped by core. But the core entry name there always has been the one from the RBF file. Until now, because I pushed a change, and now Arcade Organizer takes names.txt into consideration.

Because of this, now it makes sense to put also arcade cores in names.txt, For example jtcps1 could be Capcom CPS-1, and so on. With that, after running AO, the Cores folder will look much nicer.

**Comment by theypsilon** [comment]
Here is an example: https://twitter.com/josembarroso/status/1277670324654530567?s=20

**Comment by ThreepwoodLeBrush** [comment]
Thank you for the link. That is a clever approach and the list of arcade cores looks great with the names you added!
