### ISSUE TITLE
Would you like to generate all the .txt files from a single file for easier maintenance?

### ISSUE THREAD

**Issue by theypsilon** [ThreepwoodLeBrush/Names_MiSTer#4]
Hey @ThreepwoodLeBrush , I really appreciate your contribution maintaining these files. I know sometimes is a bit messy having to do the same change in many files at once. So is nice that we are keeping it up.

I was thinking, in order to make the maintaining of these files easier, I could develop a file format, so that we could just maintain a single file, let's say a .csv file, or a excel file, that would contain all the different version variations as columns.

Then, I could make a simple script that would generate all the .txt files from that single new formatted file. And that script could run automatically whenever it detects a change on GitHub, without having to trigger it manually. I guess that would allow making changes much easier and less time consuming.

What do you think? Do you believe this would help you during the maintenance of this repository? In that case, would you prefer an .csv or an excel file?

**Comment by ThreepwoodLeBrush** [comment]
Hi @theypsilon, thank you, that would indeed be very helpful and much more elegant than how it is done at the moment. It sounds like a great idea that would make maintaining the files a lot easier and less prone to errors. As file format I would vote for a non-proprietary format, thus I suggest .csv.

Also a thank you to you for maintaining the arcade core names, I have not worked on these at all.

**Comment by theypsilon** [comment]
What do you think about this format?

https://gist.github.com/theypsilon/454ffb3e8aafecedcf13b1a4935899ad

Notice that some values are referencing previous columns of the same row, when there is a previous value identical in the same row.

**Comment by ThreepwoodLeBrush** [comment]
I found nothing that would need to be different in my opinion. It is well laid out and more than suitable for the job. Good thinking with the referencing of other columns within the file.

**Comment by theypsilon** [comment]
It's done.

From now on, you only need to care about updating this file: https://github.com/ThreepwoodLeBrush/Names_MiSTer/blob/master/names.csv

Also, don't need to care about formatting because it will regenerate the file once you have committed with the proper format.

The automatic task takes around 1 minute after you've sent the changes to GitHub.

**Comment by theypsilon** [comment]
Closing
