### ISSUE TITLE
Rename IBM 386-Compatible

### ISSUE THREAD

**Issue by theypsilon** [ThreepwoodLeBrush/Names_MiSTer#5]
At this point, it should probably be IBM 486-Compatible?

**Comment by ThreepwoodLeBrush** [comment]
True. I am not sure if it should bear the brand "IBM", though. I have to read up on the history of the chip to see if it should now be "Intel". I would also make it "486SX", to clarify that it has not FPU.

Let me do some research, then I will post here again.

**Comment by ThreepwoodLeBrush** [comment]
Okay, I would do the following:

Rename "IBM 386-Compatible" to "IBM PC Compatible" for the manufacturer variants, which works for the 18 Character names.txt and "PC Compatible" for the "common" variants.

The CHAR28 variants I would rename to "IBM PC Compatible (486SX)" and "PC Compatible (486SX)".

After all it is not about the chip in specific, but the computer standard it is compatible to.

Would you agree?

**Comment by theypsilon** [comment]
I've been gathering some feedback, and it seems that the term IBM PC Compatible is a bit too broad. It could happen that somebody soon tries to publish a XT core. Or any other core in between for the PC family. Therefore, I think it should include 486 in the name because that would describe which software is compatible with that core.

**Comment by ThreepwoodLeBrush** [comment]
Fair enough. How about "PC (486SX)" for CHAR18_Common, "IBM PC (486SX)" for CHAR18_Manufacturer and "IBM PC Compatible (486SX)" for CHAR28_Manufacturer etc?

**Comment by theypsilon** [comment]
I think that sounds good.

**Comment by theypsilon** [comment]
I've seen the change has been made, I'll close the issue 🙂
