### ISSUE TITLE
Support for LLAPI cores

### ISSUE THREAD

**Issue by calle81** [ThreepwoodLeBrush/Names_MiSTer#6]
Hi,

I would be very happy if we could change the LLAPI cores names to follow the standard core naming convention with an added #LLAPI. I download the LLAPI cores into the standard core directories and as it is now it gets messy with different names for the same cores.

Here are my proposed changes:

Gameboy_LLAPI:      Game Boy/Color #LLAPI
GBA_LLAPI:          Game Boy Advance #LLAPI
Genesis_LLAPI:      Mega Drive #LLAPI
MegaCD_LLAPI:       Mega-CD #LLAPI
NeoGeo_LLAPI:       Neo Geo MVS/AES #LLAPI
NES_LLAPI:          NES #LLAPI
SMS_LLAPI:          Master System #LLAPI
SNES_LLAPI:         Super NES #LLAPI
TurboGrafx16_LLAPI: PC Engine Duo #LLAPI
Pacman_LLAPI:       Namco - Pac-Man #LLAPI 

Kind regards,
Carl

**Comment by ThreepwoodLeBrush** [comment]
Hello @calle81, I am afraid your suggested changes are too long for the 18-Character names.txt-files. The names would start scrolling while the premise of the files here is to not have the names scroll. It is why they were shortened in the first place.

Instead please download and customize the names.txt of your choice to suite your specific needs.
