### ISSUE TITLE
Feedback about references in names.csv

### ISSUE THREAD

**Issue by theypsilon** [ThreepwoodLeBrush/Names_MiSTer#7]
I'm starting to think that having references in names.csv might not be the best, because by looking at the file now, it is kind of very noisy, and thus harder to understand.

The good thing about them is that is easier to change one cell and having that change being reflected in all the other columns.

But not 100% sure that the trade-off is worth it.

What do you think?

**Comment by ThreepwoodLeBrush** [comment]
It may be harder to understand, but I expect it to be less work once you get use to it. I would at least not toss it out yet and try it for a while.
