### ISSUE TITLE
I've found a contributor for Arcade names

### ISSUE THREAD

**Issue by theypsilon** [ThreepwoodLeBrush/Names_MiSTer#8]
Hi Threepwood, a good friend of mine would like to help with the names of the Arcade cores.

His GitHub user is https://github.com/PigSaint

Could you please add him as a contributor? I will take responsibility for any change he will be doing on the project.

**Comment by ThreepwoodLeBrush** [comment]
Hi Theypsilon, thank you, I gladly added him.

@PigSaint welcome aboard and thank you for volunteering. Feel free to suggest name improvements for all systems, not only arcade.

**Comment by PigSaint** [comment]
My Pleasure! I'm glad to be here. I'll do my best.
