### ISSUE TITLE
Core name change for Atari 2600 and 7800

### ISSUE THREAD

**Issue by theypsilon** [ThreepwoodLeBrush/Names_MiSTer#9]
The author requested a change in the name of the cores:

2600 -> Atari 2600 (Old)
7800 -> Atari 2600/7800

I thought that you would be ok with that, so I hope you don't mind that I changed it already. Maybe some correction in the spelling should be done for consistency, though.

The 7800 core also implements 2600, and it's more advanced, that's why people should try to look for playing 2600 in the 7800 core.

**Comment by Kitrinx** [comment]
I would appreciate this

**Comment by ThreepwoodLeBrush** [comment]
Of course and thanks for requesting this change.

"Atari 2600/7800" is in line with the naming of other multi system cores and fits all length versions.

I would suggest to name the old core "Atari 2600 (Deprecated)" in the 28 and 54 character long variants.

Did you have any other correction in spelling in mind that I missed?

**Comment by theypsilon** [comment]
Not from my side, thanks.

**Comment by Kitrinx** [comment]
Will the average person seeing it understand the meaning of "Deprecated"?

**Comment by ThreepwoodLeBrush** [comment]
I have no doubt that the MiSTer's target audience is tech savvy enough to have heard this term before, it is the correct term to use here. Besides, it is easy to look up :)

Thanks again for pointing out these changes, it is much appreciated! They have been implemented and as such I am closing this ticket now. Feel free to open a new ticket if there is anything else we can help with.
